### ISSUE TITLE
loop is not starting

### ISSUE THREAD

**Issue by 44bit23** [vtcbca/basic-programming-44bit23#2]
in assignment 7 my loop is not starting

**Comment by 81bit23** [comment]
your condition may be wrong

**Comment by 44bit23** [comment]
what do yo mean by it.

**Comment by 81bit23** [comment]
what is your innitial value and condition for the loop?

**Comment by 44bit23** [comment]
innitial???

**Comment by 81bit23** [comment]
are loop ki strting kha se kar rahe ho?

**Comment by 42bit23** [comment]
tujhe innitial ka matlb nai pata....

**Comment by 44bit23** [comment]
strting??

**Comment by 81bit23** [comment]
sorry starting

**Comment by 42bit23** [comment]
okkaayyyyy

**Comment by 44bit23** [comment]
start  i=0 he.

**Comment by 81bit23** [comment]
or condition?

**Comment by 44bit23** [comment]
i>0

**Comment by 93bit23** [comment]
loop konsi luu while ya for??

**Comment by 81bit23** [comment]
are ye to hammesa wrong hi rahega na dimag chalao zara.

**Comment by 44bit23** [comment]
93bhai jo bhi lo chaleha

**Comment by 44bit23** [comment]
bas condition true honi chahie

**Comment by 93bit23** [comment]
ookay bhai

**Comment by 81bit23** [comment]
lagta he samaj me aa gya

**Comment by 44bit23** [comment]
ha aa gya thank you.

**Comment by 44bit23** [comment]
mene i=0,i<n,i++ liya

**Comment by 93bit23** [comment]
par ye loop me dimag ghum jata hai specially woh pattern vale me!!

**Comment by 44bit23** [comment]
are ezy he bas practice karo.

**Comment by 93bit23** [comment]
arre bhai concept hii clear nahi hai

**Comment by 44bit23** [comment]
to jake you tube pa concept clear kar

**Comment by 93bit23** [comment]
ookay bhai
