### ISSUE TITLE
wrong pattern

### ISSUE THREAD

**Issue by 98bit23** [vtcbca/basic-programming-44bit23#3]
getting wrong pattern in alphabet pattern
A
ABC
ABCDE

**Comment by 76bit23** [comment]
yeah its like 
A
AB 
ABC
ABCD

**Comment by 98bit23** [comment]
lagta he tere bhi number he
 ek baar jake dekh asignment dekh

**Comment by 76bit23** [comment]
arre bhai ye kya??

**Comment by 98bit23** [comment]
assignment me 
A
ABA
ABCBA he.

**Comment by 76bit23** [comment]
bhai pattern toh bohat sarre hai

**Comment by 98bit23** [comment]
lekin bas assignment mese karni h problems.

**Comment by 76bit23** [comment]
thik hai bhai

**Comment by 37bit23** [comment]
are bas jab tum string k middle me se decrement karna suru kar do.

**Comment by 76bit23** [comment]
assignment kon padh hai wo toh bus copy paste karte hai hum log

**Comment by 98bit23** [comment]
ha vahi karta hu

**Comment by 37bit23** [comment]
aur space mat bhulana

**Comment by 76bit23** [comment]
arre yaar ek toh ye pattern vale me kitne errors aati hai

**Comment by 98bit23** [comment]
ayegi hi na, focus nahi he tumara.

**Comment by 76bit23** [comment]
uss ache toh if else vale hote hai

**Comment by 98bit23** [comment]
ha vo to he
